language: python
env:
  global:
  - secure: eVYI9c4v/gdgMu9/HUrdOljH6xoWucjRNlQMfh24LA3g6j1dr52+SdCP59mzFqBiAIR8eBtipIkit23sQDn+ulw3bJSrLszXsWCKGywLVG/6QtgsqN9J17/RbUA2ZnfA86famA6Z4+CtJbW7nQPYidRQshPC85iiekftN9DwdeQ=
  - secure: a+hf3j24x0fyP8OP/8IiIp5aMn+GfYxf97vWtJV1U76J8eGNLyj+n/AsPx4y6OpRWy2qTf/90W5TxU/ruRxKRl3j78+W2sYCI1LiQIlNlVX6tMrLnm2YS5zvwH3jICCmRUmY7d0Vc5MrqBRoKnmA+1QqyDrdiCjWkNSh6Jcn5KA=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes wget git-core pkg-config cmake python-dev python-support liblapack-dev libatlas-base-dev libblitz1-dev libavformat-dev libavcodec-dev libswscale-dev libboost-all-dev libmatio-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev libhdf5-serial-dev libfftw3-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended libsvm-dev libvl-dev dvipng python-numpy python-scipy dvipng libopencv-dev gfortran
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy==1.9.2 matplotlib coverage cpp-coveralls scipy==0.15.1
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob import get_config; print(get_config())'
- ./bin/coverage run --source=bob ./bin/nosetests bob.ip bob.learn bob.io bob.blitz bob.ap bob.core bob.db bob.math bob.sp bob.measure -sv --first-package-wins
#- ./bin/sphinx-build -b doctest doc sphinx
#- ./bin/sphinx-build -b html doc sphinx
after_success:
#- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
#- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
##- ./upload-sphinx.sh
#- ./upload-wheel.sh
